#!/bin/sh

# Usage: $0
# Print the selo4 font (a Glyph16 font with latin and pseudograhics)

. "$KONPU_HOME"/tools/dev/lib/common.sh
cd "$KONPU_HOME"/tools/selo/fonts.in || die 'cannot cd into fonts.in'
requires glyph-generate-octants

dev-cpp << EOF
#include "selo"
#define  ASCII_SIZE 4
#include "selo_ascii"
EOF
glyph-generate-octants 16 | awk '{print $1, $2}'
