// Generate the colors information in ilo Konpu's ROM.

#include "kule.h"
#include "kule-kdtree.h"
#include "kule-konpu.h"

// Return the tree node which represents a given color index.
static const Node *find_node(const Node *node, int color)
{
   if (node == NULL) return NULL;
   if (node->color == color) return node;
   const Node *from_left = find_node(node->left, color);
   if (from_left != NULL) return from_left;
   return find_node(node->right, color);
}

int main(void)
{
   Palette pal = PaletteKonpu();
   Node* kdtree = TreeInit(pal);

   printf("   // Color Palette: OkLab components multiplied by 510 and rounded to 8-bits\n");
   printf("   // + space-partitioning k-d tree info on the palette in L,a,b space [note:\n");
   printf("   // (median) color 127 means no child node] + 8-bits gamma sRGB components.\n");
   printf("   // Generated by `kule-generate-konpu-rom` (see: tools/kule).\n");
   printf("   //\n");
   printf("   // Color #|OkLab: L/2, a-12,  b+30 |kd: left, right |RGB: R,   G,   B\n");
   printf("   //--------|------------------------|----------------|-----------------\n");

   for (int i = 0; i < pal.size; i++) {
      const Node *node = find_node(kdtree, i);
      assert(node != NULL);
      printf("   /*  %3d  */       %3d, %4d, %4d  ,     %3d, %3d   ,   %3d, %3d, %3d,\n",
         i,
         // OkLab components:
         (int) roundf(pal.color[i].L *  255),
         (int) roundf(pal.color[i].a * (255 * 2) - 12),
         (int) roundf(pal.color[i].b * (255 * 2) + 30),
         // k-d tree information:
         (node->left)?  node->left->color  : 127,
         (node->right)? node->right->color : 127,
         // gamma sRGB components:
          PaletteKonpuSRGB[i] >> 16,
         (PaletteKonpuSRGB[i] >> 8) & 0xFF,
          PaletteKonpuSRGB[i] & 0xFF
      );
   }

   TreeDrop(kdtree);
   return EXIT_SUCCESS;
}
