// Helpers for writing C string literals using sitelen pona.
// TODO CHANGE THOSE TO SITELEN PONA CHARACTERS

#ifndef KONPU_LITERALS_H
#define KONPU_LITERALS_H

// nimi 128-247 ("classic 120 pu")
#define A                "a "
#define AKESI            "akesi "
#define ALA              "ala "
#define ALASA            "alasa "
#define ALE              "ale "
#define ANPA             "anpa "
#define ANTE             "ante "
#define ANU              "anu "
#define AWEN             "awen "
#define E                "e "   // Note: Names starting with E are reserved in C
#define EN               "en "  //      and POSIX, which use such names to macro
#define ESUN             "esun " //     constants that can be assigned to errno.
#define IJO              "ijo "
#define IKE              "ike "
#define ILO              "ilo "
#define INSA             "insa "
#define JAKI             "jaki "
#define JAN              "jan "
#define JELO             "jelo "
#define JO               "jo "
#define KALA             "kala "
#define KALAMA           "kalama "
#define KAMA             "kama "
#define KASI             "kasi "
#define KEN              "ken "
#define KEPEKEN          "kepeken "
#define KILI             "kili "
#define KIWEN            "kiwen "
#define KO               "ko "
#define KON              "kon "
#define KULE             "kule "
#define KULUPU           "kulupu "
#define KUTE             "kute "
#define LA               "la "
#define LAPE             "lape "
#define LASO             "laso "
#define LAWA             "lawa "
#define LEN              "len "
#define LETE             "lete "
#define LI               "li "
#define LILI             "lili "
#define LINJA            "linja "
#define LIPU             "lipu "
#define LOJE             "loje "
#define LON              "lon "
#define LUKA             "luka "
#define LUKIN            "lukin "
#define LUPA             "lupa "
#define MA               "ma "
#define MAMA             "mama "
#define MANI             "mani "
#define MELI             "meli "
#define MI               "mi "
#define MIJE             "mije "
#define MOKU             "moku "
#define MOLI             "moli "
#define MONSI            "monsi "
#define MU               "mu "
#define MUN              "mun "
#define MUSI             "musi "
#define MUTE             "mute "
#define NANPA            "nanpa "
#define NASA             "nasa "
#define NASIN            "nasin "
#define NENA             "nena "
#define NI               "ni "
#define NIMI             "nimi "
#define NOKA             "noka "
#define O                "o "
#define OLIN             "olin "
#define ONA              "ona "
#define OPEN             "open "
#define PAKALA           "pakala "
#define PALI             "pali "
#define PALISA           "palisa "
#define PAN              "pan "
#define PANA             "pana "
#define PI               "pi "
#define PILIN            "pilin "
#define PIMEJA           "pimeja "
#define PINI             "pini "
#define PIPI             "pipi "
#define POKA             "poka "
#define POKI             "poki "
#define PONA             "pona "
#define PU               "pu "
#define SAMA             "sama "
#define SELI             "seli "
#define SELO             "selo "
#define SEME             "seme "
#define SEWI             "sewi "
#define SIJELO           "sijelo "
#define SIKE             "sike "
#define SIN              "sin "
#define SINA             "sina "
#define SINPIN           "sinpin "
#define SITELEN          "sitelen "
#define SONA             "sona "
#define SOWELI           "soweli "
#define SULI             "suli "
#define SUNO             "suno "
#define SUPA             "supa "
#define SUWI             "suwi "
#define TAN              "tan "
#define TASO             "taso "
#define TAWA             "tawa "
#define TELO             "telo "
#define TENPO            "tenpo "
#define TOKI             "toki "
#define TOMO             "tomo "
#define TU               "tu "
#define UNPA             "unpa "
#define UTA              "uta "
#define UTALA            "utala "
#define WALO             "walo "
#define WAN              "wan "
#define WASO             "waso "
#define WAWA             "wawa "
#define WEKA             "weka "
#define WILE             "wile "
// nimi 248-255:
#define MONSUTA          "monsuta "
#define NAMAKO           "namako "
#define TONSI            "tonsi "
#define KIN              "kin "
#define KIPISI           "kipisi "
#define N                "n "
#define LEKO             "leko "
#define KIJETESANTAKALU  "kijetesantakalu "
// ali
#define ALI              ALE // ????
// extra
#define MAJUNA           "majuna "
#define OKO              "oko "
#define KU               "ku "
#define SU               "su "
#define MISIKEKE         "misikeke "
#define SOKO             "soko "
//
#define LANPAN           "lanpan "
#define LINLUWI          "linluwi "
#define EPIKU            "epiku "
#define KOKOSILA         "kokosila "
#define MESO             "meso "
#define JASIMA           "jasima "
// Punctuation
#define TE               "\""
#define TO               "\""
#define OPEN_NIMI        "["
#define PINI_NIMI        "]"
#define SIKE_PINI        "."
#define SIKE_TU          ":"



#endif
