#ifndef  KONPU_GLYPH_PATTERNS_BASICS_H
#define  KONPU_GLYPH_PATTERNS_BASICS_H
#include "glyph.h"

//------------------------------------------------------------------------------
// Glyph Block Constants:
// GLYPH<n>_PATTERN_QUADRANT_<TOP|BOTTOM>_<LEFT|RIGHT>
// GLYPH<n>_PATTERN_HALF_<TOP|BOTTOM|LEFT|RIGHT>
// GLYPH<n>_PATTERN_<FULL|EMPTY>
//
// This is a bit similar to Unicode "Block Elements"
//------------------------------------------------------------------------------

#define GLYPH8_PATTERN_QUADRANT_TOP_LEFT        GLYPH8(a0)
#define GLYPH8_PATTERN_QUADRANT_TOP_RIGHT       GLYPH8(50)
#define GLYPH8_PATTERN_QUADRANT_BOTTOM_LEFT     GLYPH8(0a)
#define GLYPH8_PATTERN_QUADRANT_BOTTOM_RIGHT    GLYPH8(05)
#define GLYPH8_PATTERN_HALF_TOP                 ((Glyph8)(GLYPH8_PATTERN_QUADRANT_TOP_LEFT|GLYPH8_PATTERN_QUADRANT_TOP_RIGHT))
#define GLYPH8_PATTERN_HALF_BOTTOM              ((Glyph8)(GLYPH8_PATTERN_QUADRANT_BOTTOM_LEFT|GLYPH8_PATTERN_QUADRANT_BOTTOM_RIGHT))
#define GLYPH8_PATTERN_HALF_LEFT                ((Glyph8)(GLYPH8_PATTERN_QUADRANT_TOP_LEFT|GLYPH8_PATTERN_QUADRANT_BOTTOM_LEFT))
#define GLYPH8_PATTERN_HALF_RIGHT               ((Glyph8)(GLYPH8_PATTERN_QUADRANT_TOP_RIGHT|GLYPH8_PATTERN_QUADRANT_BOTTOM_RIGHT))
#define GLYPH8_PATTERN_FULL                     GLYPH8(ff)
#define GLYPH8_PATTERN_EMPTY                    GLYPH8(0)

#define GLYPH16_PATTERN_QUADRANT_TOP_LEFT       GLYPH16(0033)
#define GLYPH16_PATTERN_QUADRANT_TOP_RIGHT      GLYPH16(00cc)
#define GLYPH16_PATTERN_QUADRANT_BOTTOM_LEFT    GLYPH16(3300)
#define GLYPH16_PATTERN_QUADRANT_BOTTOM_RIGHT   GLYPH16(cc00)
#define GLYPH16_PATTERN_HALF_TOP                ((Glyph16)(GLYPH16_PATTERN_QUADRANT_TOP_LEFT|GLYPH16_PATTERN_QUADRANT_TOP_RIGHT))
#define GLYPH16_PATTERN_HALF_BOTTOM             ((Glyph16)(GLYPH16_PATTERN_QUADRANT_BOTTOM_LEFT|GLYPH16_PATTERN_QUADRANT_BOTTOM_RIGHT))
#define GLYPH16_PATTERN_HALF_LEFT               ((Glyph16)(GLYPH16_PATTERN_QUADRANT_TOP_LEFT|GLYPH16_PATTERN_QUADRANT_BOTTOM_LEFT))
#define GLYPH16_PATTERN_HALF_RIGHT              ((Glyph16)(GLYPH16_PATTERN_QUADRANT_TOP_RIGHT|GLYPH16_PATTERN_QUADRANT_BOTTOM_RIGHT))
#define GLYPH16_PATTERN_FULL                    GLYPH16(ffff)
#define GLYPH16_PATTERN_EMPTY                   GLYPH16(0)

#define GLYPH32_PATTERN_QUADRANT_TOP_LEFT       GLYPH32(00003333)
#define GLYPH32_PATTERN_QUADRANT_TOP_RIGHT      GLYPH32(0000cccc)
#define GLYPH32_PATTERN_QUADRANT_BOTTOM_LEFT    GLYPH32(33330000)
#define GLYPH32_PATTERN_QUADRANT_BOTTOM_RIGHT   GLYPH32(cccc0000)
#define GLYPH32_PATTERN_HALF_TOP                ((Glyph32)(GLYPH32_PATTERN_QUADRANT_TOP_LEFT|GLYPH32_PATTERN_QUADRANT_TOP_RIGHT))
#define GLYPH32_PATTERN_HALF_BOTTOM             ((Glyph32)(GLYPH32_PATTERN_QUADRANT_BOTTOM_LEFT|GLYPH32_PATTERN_QUADRANT_BOTTOM_RIGHT))
#define GLYPH32_PATTERN_HALF_LEFT               ((Glyph32)(GLYPH32_PATTERN_QUADRANT_TOP_LEFT|GLYPH32_PATTERN_QUADRANT_BOTTOM_LEFT))
#define GLYPH32_PATTERN_HALF_RIGHT              ((Glyph32)(GLYPH32_PATTERN_QUADRANT_TOP_RIGHT|GLYPH32_PATTERN_QUADRANT_BOTTOM_RIGHT))
#define GLYPH32_PATTERN_FULL                    GLYPH32(ffffffff)
#define GLYPH32_PATTERN_EMPTY                   GLYPH32(0)

#define GLYPH64_PATTERN_QUADRANT_TOP_LEFT       GLYPH64(000000000f0f0f0f)
#define GLYPH64_PATTERN_QUADRANT_TOP_RIGHT      GLYPH64(00000000f0f0f0f0)
#define GLYPH64_PATTERN_QUADRANT_BOTTOM_LEFT    GLYPH64(0f0f0f0f00000000)
#define GLYPH64_PATTERN_QUADRANT_BOTTOM_RIGHT   GLYPH64(f0f0f0f000000000)
#define GLYPH64_PATTERN_HALF_TOP                ((Glyph64)(GLYPH64_PATTERN_QUADRANT_TOP_LEFT|GLYPH64_PATTERN_QUADRANT_TOP_RIGHT))
#define GLYPH64_PATTERN_HALF_BOTTOM             ((Glyph64)(GLYPH64_PATTERN_QUADRANT_BOTTOM_LEFT|GLYPH64_PATTERN_QUADRANT_BOTTOM_RIGHT))
#define GLYPH64_PATTERN_HALF_LEFT               ((Glyph64)(GLYPH64_PATTERN_QUADRANT_TOP_LEFT|GLYPH64_PATTERN_QUADRANT_BOTTOM_LEFT))
#define GLYPH64_PATTERN_HALF_RIGHT              ((Glyph64)(GLYPH64_PATTERN_QUADRANT_TOP_RIGHT|GLYPH64_PATTERN_QUADRANT_BOTTOM_RIGHT))
#define GLYPH64_PATTERN_FULL                    GLYPH64(ffffffffffffffff)
#define GLYPH64_PATTERN_EMPTY                   GLYPH64(0)

#define GLYPH128_PATTERN_QUADRANT_TOP_LEFT      ((Glyph128){.top    = GLYPH64_PATTERN_HALF_LEFT})
#define GLYPH128_PATTERN_QUADRANT_TOP_RIGHT     ((Glyph128){.top    = GLYPH64_PATTERN_HALF_RIGHT})
#define GLYPH128_PATTERN_HALF_TOP               ((Glyph128){.top    = GLYPH64_PATTERN_FULL})
#define GLYPH128_PATTERN_QUADRANT_BOTTOM_LEFT   ((Glyph128){.bottom = GLYPH64_PATTERN_HALF_LEFT})
#define GLYPH128_PATTERN_QUADRANT_BOTTOM_RIGHT  ((Glyph128){.bottom = GLYPH64_PATTERN_HALF_RIGHT})
#define GLYPH128_PATTERN_HALF_BOTTOM            ((Glyph128){.bottom = GLYPH64_PATTERN_FULL})
#define GLYPH128_PATTERN_HALF_LEFT              ((Glyph128){.top = GLYPH64_PATTERN_HALF_LEFT , .bottom = GLYPH64_PATTERN_HALF_LEFT})
#define GLYPH128_PATTERN_HALF_RIGHT             ((Glyph128){.top = GLYPH64_PATTERN_HALF_RIGHT, .bottom = GLYPH64_PATTERN_HALF_RIGHT})
#define GLYPH128_PATTERN_FULL                   ((Glyph128){.top = GLYPH64_PATTERN_FULL , .bottom = GLYPH64_PATTERN_FULL})
#define GLYPH128_PATTERN_EMPTY                  ((Glyph128){0})

#define GLYPH256_PATTERN_QUADRANT_TOP_LEFT      ((Glyph256){.top_left     = GLYPH64_PATTERN_FULL})
#define GLYPH256_PATTERN_QUADRANT_TOP_RIGHT     ((Glyph256){.top_right    = GLYPH64_PATTERN_FULL})
#define GLYPH256_PATTERN_QUADRANT_BOTTOM_LEFT   ((Glyph256){.bottom_left  = GLYPH64_PATTERN_FULL})
#define GLYPH256_PATTERN_QUADRANT_BOTTOM_RIGHT  ((Glyph256){.bottom_right = GLYPH64_PATTERN_FULL})
#define GLYPH256_PATTERN_HALF_TOP               ((Glyph256){.top_left     = GLYPH64_PATTERN_FULL, .top_right    = GLYPH64_PATTERN_FULL})
#define GLYPH256_PATTERN_HALF_BOTTOM            ((Glyph256){.bottom_left  = GLYPH64_PATTERN_FULL, .bottom_right = GLYPH64_PATTERN_FULL})
#define GLYPH256_PATTERN_HALF_LEFT              ((Glyph256){.top_left     = GLYPH64_PATTERN_FULL, .bottom_left  = GLYPH64_PATTERN_FULL})
#define GLYPH256_PATTERN_HALF_RIGHT             ((Glyph256){.top_right    = GLYPH64_PATTERN_FULL, .bottom_right = GLYPH64_PATTERN_FULL})
#define GLYPH256_PATTERN_FULL                   ((Glyph256){.top_left     = GLYPH64_PATTERN_FULL, .top_right    = GLYPH64_PATTERN_FULL,\
                                                            .bottom_left  = GLYPH64_PATTERN_FULL, .bottom_right = GLYPH64_PATTERN_FULL})
#define GLYPH256_PATTERN_EMPTY                  ((Glyph256){0})

#endif //KONPU_GLYPH_PATTERNS_BASICS_H
